spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081