version: "3.9"

services:

  postgres:

    image: postgres:17

    container_name: postgres

    environment:
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  redis:

    image: redis:7

    container_name: redis

    ports:
      - "6379:6379"